#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYPROJECT_FILE="$PROJECT_ROOT/pyproject.toml"
LOCK_FILE="$PROJECT_ROOT/uv.lock"
VENV_DIR="/home/vscode/.venv"
STAMP_FILE="$VENV_DIR/.setup.stamp"
BASHRC_FILE="/home/vscode/.bashrc"
CUDA_ENV_FILE="$VENV_DIR/.cuda_env.sh"

echo "== Setup: ensure home venv at $VENV_DIR =="

if [ ! -x "$VENV_DIR/bin/python" ]; then
  python -m venv "$VENV_DIR"
fi

# Ensure interactive terminals auto-enter the project venv.
if ! grep -q 'source /home/vscode/.venv/bin/activate' "$BASHRC_FILE"; then
  printf '\n# Auto-activate project virtual environment\nsource /home/vscode/.venv/bin/activate\n' >> "$BASHRC_FILE"
fi

if ! "$VENV_DIR/bin/python" -m pip --version >/dev/null 2>&1; then
  "$VENV_DIR/bin/python" -m ensurepip --upgrade
fi
"$VENV_DIR/bin/python" -m pip install -U pip wheel setuptools

export UV_PROJECT_ENVIRONMENT="$VENV_DIR"
export UV_CACHE_DIR="/home/vscode/.cache/uv"
cd "$PROJECT_ROOT"

if ! command -v uv >/dev/null 2>&1; then
  echo "uv is not installed; aborting." >&2
  exit 1
fi

HASH_INPUT="$(cat "$PYPROJECT_FILE")"
if [ -f "$LOCK_FILE" ]; then
  HASH_INPUT="$HASH_INPUT$(cat "$LOCK_FILE")"
fi
CURRENT_HASH="$(printf "%s" "$HASH_INPUT" | sha256sum | awk '{print $1}')"

if [ -f "$STAMP_FILE" ] && grep -q "$CURRENT_HASH" "$STAMP_FILE"; then
  echo "== Dependencies already installed (pyproject/lock unchanged) =="
else
  echo "== Installing project dependencies with uv =="
  uv sync --no-dev --python "$VENV_DIR/bin/python"
  echo "== Registering ipykernel =="
  "$VENV_DIR/bin/python" -m ipykernel install --user --name "project-venv" --display-name "Python (.venv)"
  echo "$CURRENT_HASH" > "$STAMP_FILE"
fi

# Configure CUDA/XLA environment from the actual venv interpreter path.
"$VENV_DIR/bin/python" - <<'PY' > "$CUDA_ENV_FILE"
import glob
import os
import site

site_packages = next(p for p in site.getsitepackages() if "site-packages" in p)
cuda_home = os.path.join(site_packages, "nvidia", "cuda_nvcc")
lib_dirs = sorted(glob.glob(os.path.join(site_packages, "nvidia", "*", "lib")))

print("# Auto-generated by .devcontainer/setup.sh")
print(f'export CUDA_HOME="{cuda_home}"')
print(f'export XLA_FLAGS="--xla_gpu_cuda_data_dir={cuda_home}"')
print(f'export PATH="{cuda_home}/bin:${{PATH}}"')
print(f'export LD_LIBRARY_PATH="{":".join(lib_dirs)}:${{LD_LIBRARY_PATH:-}}"')
PY

if ! grep -q 'source /home/vscode/.venv/.cuda_env.sh' "$BASHRC_FILE"; then
  printf '\n# Auto-configure CUDA/XLA paths from the active project virtual environment\nsource /home/vscode/.venv/.cuda_env.sh\n' >> "$BASHRC_FILE"
fi

echo "== Setup complete =="
